name: On Release

on:
  release:
    types: [published, edited]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Fetch release name"
        run: |
          echo "NAME=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        id: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: "Log version"
        run: echo $( gh release list --limit 1 )
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
      
      - name: "Create new label on release"
        run: gh label create "release-${{ env.NAME }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: "Read Release"
        run: echo $( gh release view )
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
