name: On Release

on:
  release:
    types: [created, published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Fetch release name"
        run: echo "name=$( gh release list --limit 1 )" >> $GITHUB_OUTPUT
        id: release
      
      - name: "Create new label on release"
        run: gh label create "release-$(steps.release.outputs.name)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
