name: On Release

on:
  release:
    types: [created, published, edited]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Fetch release name"
        run: echo "NAME=$( gh release list --limit 1 )" >> $GITHUB_ENV
        id: release
      
      - name: "Create new label on release"
        run: gh label create "release-$NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
